'''
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_d = dict(collections.Counter(s))
        t_d = dict(collections.Counter(t))
        if len(t_d) > len(s_d):
            t_d, s_d =  s_d, t_d
        
        for key in s_d:
            if key in t_d:
                if s_d[key] == t_d[key]:
                    continue
                else:
                    return key
            else:
                return key
